config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('feets/', include('feets.urls', namespace='feets')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('workshops/', include('workshops.urls', namespace='workshops')),
    path('knees/', include('knees.urls', namespace='knees')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path('', views.Home, name='home'),
    path('guide/', views.Guide, name='guide'),
    path('guide_tf', views.GuideTf, name='guide_tf'),
    path('guide_tt', views.GuideTt, name='guide_tt'),
    path('amputation', views.Amputation, name='amputation'),
    path('search', views.Search, name='search'),
    path('userstory', views.UserStory, name='userstory'),
    path('admin_page', views.AdminPage, name='admin-page'),

]

feets/urls.py
from django.shortcuts import render
from django.urls import path
from knees import views
from . import views


app_name = 'feets'

urlpatterns = [
    path('', views.FeetPage, name="feets"),
    path('search/', views.search, name='search'),
    path('<int:pk>/', views.FeetDetailView.as_view(), name='feet-detail'),
    path('feets_list_all', views.FeetListAllFilter, name='feets-list-all'),
    path('feets_admin_list/', views.FeetAdminListView.as_view(), name='feets-admin-list'),
    path('feets_admin_list/<int:pk>/', views.FeetAdminUpdateView.as_view(), name='feet-admin-update'),
]

feets/models.py
from django.db import models
from django.db.models.fields.files import ImageField
from django.db.models.fields.related import ManyToManyField

# Create your models here.

class AbstractItem(models.Model):
    name = models.CharField(max_length=50, default="", blank=True)
    created = models.DateTimeField(auto_now_add=True, blank=True)
    updated = models.DateTimeField(auto_now=True, blank=True)
    class Meta:
        abstract = True

    def __str__(self):
        return self.name

class MobisGrade(AbstractItem):
    pass

class Weight(AbstractItem):
    pass

class Activity(AbstractItem):
    pass

class Function(AbstractItem):
    pass

class Age(AbstractItem):
    pass

class Hope(AbstractItem):
    pass

class Brand(AbstractItem):
    pass

class Rating(AbstractItem):
    pass

class Waterproof(AbstractItem):
    pass

class Feet(models.Model):
    code = models.CharField(max_length=50)
    name = models.CharField(max_length=50, blank=True)
    description = models.TextField(blank=True)
    feet_image = models.ImageField(upload_to='feets',blank=True)
    mobis_grade = models.ManyToManyField(MobisGrade, related_name="feets", blank=True)
    weight = models.ManyToManyField(Weight, related_name="feets", blank=True)
    activity = models.ManyToManyField(Activity, related_name='feets', blank=True)
    function = models.ManyToManyField(Function, related_name='feets', blank=True)
    age = models.ManyToManyField(Age, related_name='feets', blank=True)
    hope = models.ManyToManyField(Hope, related_name='feets', blank=True)
    brand = models.ManyToManyField(Brand, related_name='feets', blank=True)
    rating = models.ManyToManyField(Rating, related_name='feets', blank=True)
    waterproof = models.ManyToManyField(Waterproof, related_name='feets', blank=True)

    def __str__(self):
        return self.name

feets/forms.py
from django import forms
from django.db.models.query_utils import Q
from . import models

class SearchForm(forms.Form):

    activity = forms.ModelChoiceField(queryset=models.Activity.objects.all())
    waterproof = forms.ModelChoiceField(queryset=models.Waterproof.objects.all())
    hope = forms.ModelChoiceField(queryset=models.Hope.objects.all())
    age = forms.ModelChoiceField(queryset=models.Age.objects.all())


class FeetFilter(forms.Form):
    function = forms.ModelMultipleChoiceField(required=False, queryset=models.Function.objects.all())
    brand = forms.ModelMultipleChoiceField(required=False, queryset=models.Brand.objects.all())
    mobis_grade = forms.ModelMultipleChoiceField(required=False, queryset=models.MobisGrade.objects.all())
    rating = forms.ModelMultipleChoiceField(required=False, queryset=models.Rating.objects.all())
    name = forms.CharField(required=False,)

class FeetAdminForm(forms.ModelForm):
    class Meta:
        model = models.Feet
        fields = [
            'code',
            'name',
            'description',
            'mobis_grade',
            'weight',
            'activity',
            'function',
            'age',
            'rating',
            'waterproof',
            'brand',
        ]

feets/views.py
from django.core import paginator
from django.views.generic import ListView, DetailView, UpdateView
from django.shortcuts import render
from django.urls import reverse
from . import models, forms
from django.core.paginator import Paginator

# def Feet(request):
#     return render(request, 'feets/feets.html')

def FeetPage(request):
    return render(request, 'feets/feets.html')


def search(request):

    form = forms.SearchForm(request.GET)

    if form.is_valid():
        activity = form.cleaned_data.get("activity")
        hope = form.cleaned_data.get("hope")
        age = form.cleaned_data.get("age")
        waterproof = form.cleaned_data.get("waterproof")
        
        filter_args = {}
        
        if activity is not None:
            filter_args["activity"] = activity

        # for a in activity:
        #     filter_args["activity"] = a
        # if activity is not None:
        #     filter_args["activity"] = activity
        
        if hope is not None:
            filter_args["hope"] = hope

        if age is not None:
            filter_args["age"] = age

        if waterproof is not None:
            filter_args["waterproof"] = waterproof


        feets = models.Feet.objects.filter(**filter_args)


    else:
        form = forms.SearchForm()
        return render(request, "feets/search.html", {"form": form})


    return render(request, "feets/feets_list.html", {"form": form, "feets": feets})



def FeetListAllFilter(request):
    form = forms.FeetFilter(request.GET)
    if form.is_valid():
        function = form.cleaned_data.get("function")
        mobis_grade = form.cleaned_data.get("mobis_grade")
        rating = form.cleaned_data.get("rating")
        name = form.cleaned_data.get("name")

        filter_args = {}
        
        for a in function:
            filter_args["function"] = a
        # if function is not None:
        #     filter_args["function"] = function

        for m in mobis_grade:
            filter_args["mobis_grade"] = m

        for r in rating:
            filter_args["rating"] = r  

        if name is not None:
            filter_args['name__contains']= name       

        qs = models.Feet.objects.filter(**filter_args).order_by('id')

        paginator = Paginator(qs, 5)

        page = request.GET.get("page", 1)

        feets = paginator.get_page(page)


        return render(request, "feets/feets_list_all.html", {"form": form, "feets": feets})

    else:
        form = forms.FeetFilter(request.GET)

    return render(request, "feets/feets_list_all.html", {"form": form,})

    

class FeetDetailView(DetailView):
    model = models.Feet
    template_name = 'feets/feet_detail.html'
    context_object_name = 'feet'
    pk_url_kwarg = 'pk'


class FeetAdminListView(ListView):
    model = models.Feet
    template_name = 'core/adminpagefeet_list.html'
    context_object_name = 'feets'


class FeetAdminUpdateView(UpdateView):
    model = models.Feet
    template_name = 'core/adminpagefeet_update.html'
    context_object_name = 'feet'
    form_class = forms.FeetAdminForm

    def get_success_url(self):
        return reverse('feets:feets-admin-list')

templates/feets/feet_detail.html
{% extends '../base.html' %}
{% load static %}

{% block style %}
<link rel='stylesheet' href='{% static 'css/feet_detail.css' %}'>
{% endblock style %}

{% block content %}
<div class='detail_title'>
    <h1>제품 상세 정보</h1>
</div>
<div class='detail_container_total'>

    <div class='back_btn'>
        <a onclick='goBack()'><i class="fas fa-arrow-left"></i> 뒤로가기</a>
    </div>
    <div class='d-flex flex-column detail_container'>
        <div class='dedatil_container_inner'>
            <div class='img_container'>
                <img class='feet_img' src='{{ feet.feet_image.url }}'>
            </div>
            <div class='data_container'>
                <div class='data_name_desc'>
                    <div class='data_name'>
                        <h3>{{ feet.name }}</h3>
                    </div>
                    <div>
                        <h4>제품 설명: </h4>
                        <h4 class='detail_description'>{{ feet.description }}</h4>
                    </div>
                </div>
                <div class='d-flex flex-row data_container_inner'>
                    <div class='data_title'>
                        <h4>제품 코드</h4>
                        <h4>활동 범위</h4>
                        <h4>최대허용체중</h4>
                        <h4>제품 분류</h4>
                    </div>
                    <div class='data_content'>
                        <h4>: {{ feet.code }}</h4>
                        <h4>: {{ feet.brand.get }}</h4>
                        <h4>: {{feet.weight.get}}</h4>
                        <h4>: {{feet.rating.get}}</h4>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock content %}

templates/feets/feets.html
{% extends '../base.html' %}
{% load static %}

{% block style %}
<link rel='stylesheet' href='{% static 'css/feets.css' %}'>
{% endblock style %}

{% block content %}


<div class='feet_container_1 d-flex' >
        <div class='d-flex feet_container_inner_1'>
                <div class='feet_inner_1'>
                        <img class='feet_inner_img' src="{% static 'images/feet_img/feet_img(2).png' %}">
                </div>
                <div class='feet_text_1 feet_text'>
                        <h1>나에게 맞는 발은?</h1>
                        <h2>나에게 필요한 기능은 무엇일까요.<br>
                            처음 사용자를 위한 발 선택 가이드
                        </h2>
                        <div class='btn_guide_start'>
                                <a href='{% url 'feets:search' %}'>시작하기</a>
                        </div>
                </div>
        </div>
</div>

<div class='feet_container_2 d-flex flex-column'>
    <div class='feet_inner_2 translate-middle'>
    </div>
    <div class='feet_text_2 translate-middle feet_text'>
        <h1>내가 찾는 제품은?</h1>
        <h2>모든 모델을<br>
        둘러 보시겠습니까? <br>
        </h2>
        <div class='btn_guide_start'>
            <a href='{% url 'feets:feets-list-all' %}'>시작하기</a>
        </div>
    </div>
</div>





{% endblock content %}


{% block jquery %}

$(document).ready(function() {
    $('.feet_inner_img').fadeIn(2000);
});


{% endblock jquery %}

templates/feets/feets_list.html
{% extends '../base.html' %}
{% load static %}

{% block style %}
<link rel='stylesheet' href='{% static 'css/feets_list.css' %}'>
{% endblock style %}

{% block content %}
<div class='container_box'>

    <div class='page_title'>
        <h1>나에게 맞는 제품은?</h1>
    </div>
    <div class='list_container d-flex flex-column'>
        <div class='return'>
            <a class='btn_reset' href='{% url 'feets:search' %}'><i class="fas fa-redo"></i> 다시하기</a>
        </div>
        {% for feet in feets %}
            <div class='border_top'>
                <div class='list_inner'>
                    <div class='list_content d-flex flex-row justify-content-between'>

                        <div class='img_text_container d-flex flex-row align-items-center'>
                            <div class='list_img'>
                                <a href="{% url 'feets:feet-detail' feet.pk %}"><img src="{{ feet.feet_image.url }}"></a>
                            </div>
                            <div class='list_text d-flex flex-column'>
                                <div class='h1'>
                                    <h1><a href="{% url 'feets:feet-detail' feet.pk %}">{{feet.name}}</a></h1>
                                </div>
                                <div class='h2'>
                                    <h2 class='pc_feet_description'><a href="{% url 'feets:feet-detail' feet.pk %}">{{feet.description}}</a></h2>
                                    <h2 class='mob_feet_description'><a href="{% url 'feets:feet-detail' feet.pk %}">{{feet.description|truncatechars:80}}</a></h2>
                                </div>
                                <div class='mob_date_container'>
                                    <h4>활동 범위:{{feet.brand.get}}/
                                        최대허용체중:{{feet.weight.get}}/
                                        제품 분류:{{feet.rating.get}}
                                </div>
                            </div>
                        </div>

                        <div class='date_container'>
                            <div class='list_data_title'>
                                <h4>활동 범위</h4>
                                <h4>최대 허용 체중</h4>
                                <h4>제품 분류</h4>
                            </div>
                            <div class='list_date_content'>
                                <h4>: {{feet.brand.get}}</h4>
                                <h4>: {{feet.weight.get}}</h4>
                                <h4>: {{feet.rating.get}}</h4>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>



{% endblock content %}

{% block jquery %}

{% endblock jquery %}

templates/feets/search.html
{% extends '../base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block style %}
<link rel='stylesheet' href='{% static 'css/feets_search.css' %}'>
{% endblock style %}




{% block content %}

<div class='background_color'>
    <div class='feet_search_container'>
        <div class='title_conteiner'>
            <h2 class='search_title'>나에게 맞는 의지 발 찾기</h2>
        </div>
        <div class='feet_search_content'>
            <p class='p_font_size start_dec'>아래 시작하기를 눌러 나에게 맞는<br>의지 발을 찾아보세요.</p>
            <div class='btn_container d-flex justify-content-center'>
                <div class='btn_size'>
                    <a class='btn_start btn_style'>시작하기</a>
                </div>
            </div>

            <form method='get'>
                {% csrf_token %}
                <div class='select_container s1'>
                    <p class='p_font_size'>Q1. 의족을 처음 착용합니까?</p>
                    <div class='d-flex flex-row justify-content-center'> 
                            <input type='radio' name='activity' value='11' id='activity_1'>
                            <label href='#'  class='form-check-label' for='activity_1'><i class="fas fa-check"></i> 네</label>
                            <input type='radio' name='activity' value='12' id='activity_2'>
                            <label class='form-check-label' for='activity_2'><i class="fas fa-check"></i> 아니오</label>
                    </div>
                    <div class='btn_container d-flex justify-content-center'>
                        <div class='btn_size'>
                            <a class='btn_style' href='{% url 'feets:search' %}'>처음부터</a>
                        </div>
                        <div class='btn_size'>
                            <a href='#' class='n1 n_hide btn_style'>다음 <i class="fas fa-arrow-right"></i></a>
                        </div>
                    </div>
                </div>

                <div class='select_container s2'>
                        <p class='p_font_size'>Q2. 방수 기능이 필요하십니까?<br>(물놀이, 샤워 등)</p>
                        <div class='d-flex flex-row justify-content-center'>
                                <input type='radio' name='waterproof' value='1' id='waterproof_1'>
                                <label class='form-check-label' for='waterproof_1'><i class="fas fa-check"></i> 네</label>
                                <input type='radio' name='waterproof' value='2' id='waterproof_2'>
                                <label class='form-check-label' for='waterproof_2'><i class="fas fa-check"></i> 아니오</label>
                        </div>
                    <div class='btn_container d-flex justify-content-center'>
                        <div class='btn_size'>
                            <a href='#' class='b2 b_hide btn_style'><i class="fas fa-arrow-left"></i> 이전</a>
                        </div>
                        <div class='btn_size'>
                            <a class='n2 n_hide btn_style'>다음 <i class="fas fa-arrow-right"></i></a>
                        </div>
                    </div>
                </div>

                <div class='select_container s3'>
                    <p class='p_font_size'>Q3. 의족을 착용한 이후에도 원하는<br>활동을 선택해주세요.</p>
                    <div class='mob_select_3 justify-content-center'>
                            <input type='radio' name='hope' value='8' id='hope_1'>
                            <label class='form-check-label' for='hope_1'><i class="fas fa-check"></i> 골프, 조깅 등 걷기</label>
                            <input type='radio' name='hope' value='7' id='hope_2'>
                            <label class='form-check-label' for='hope_2'><i class="fas fa-check"></i> 테니스, 탁구 등 실내 운동</label>
                            <input type='radio' name='hope' value='6' id='hope_3'>
                            <label class='form-check-label' for='hope_3'><i class="fas fa-check"></i> 달리기</label>
                            <input type='radio' name='hope' value='5' id='hope_4'>
                            <label class='form-check-label' for='hope_4'><i class="fas fa-check"></i> 과격한 움직임</label>
                            <input type='radio' name='hope' value='9' id='hope_5'>
                            <label class='form-check-label' for='hope_5'><i class="fas fa-check"></i> 안전한 실내 이동</label>
                    </div>
                    <div class='btn_container d-flex justify-content-center'>
                        <div class='btn_size'>
                            <a class='b3 b_hide btn_style'><i class="fas fa-arrow-left"></i> 이전</a>
                        </div>
                        <div class='btn_size'>
                            <a class='n3 n_hide btn_style'>다음 <i class="fas fa-arrow-right"></i></a>
                        </div>
                    </div>
                </div>


                <div class='select_container s4'>
                    <p class='p_font_size'>Q4. 연령대를 선택해주세요.</p>
                    <div class='mob_select_4 justify-content-center'>
                            <input type='radio' name='age' value='1' id='age_1'>
                            <label class='form-check-label' for='age_1'><i class="fas fa-check"></i> 30세 이하</label>
                            <input type='radio' name='age' value='2' id='age_2'>
                            <label class='form-check-label' for='age_2'><i class="fas fa-check"></i> 31~50세</label>
                            <input type='radio' name='age' value='3' id='age_3'>
                            <label class='form-check-label' for='age_3'><i class="fas fa-check"></i> 51~70세</label>
                            <input type='radio' name='age' value='4' id='age_4'>
                            <label class='form-check-label' for='age_4'><i class="fas fa-check"></i> 71세 이상</label>
                    </div>
                    <div class='btn_container d-flex justify-content-center'>
                        <div class='btn_size'>
                            <a class='b4 b_hide btn_style'><i class="fas fa-arrow-left"></i> 이전</a>
                        </div>
                        <div class='btn_size'>
                            <a class='btn_final btn_style'>완료 <i class="fas fa-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>





{% endblock content %}

{% block jquery %}


$('.btn_start').click(function() {
        $('.s1').fadeIn(500);
        $('.btn_start').hide();
        $('.start_dec').hide();

})

$('.n1').click(function() {
        $('.s2').fadeIn(500);
        $('.s1').hide();
})

$('.n2').click(function() {
        $('.s3').fadeIn(500);
        $('.s2').hide();
})

$('.n3').click(function() {
        $('.s4').fadeIn(500);
        $('.s3').hide();
})


$('.b2').click(function() {
    $('.s1').fadeIn(500);
    $('.s2').hide();
})

$('.b3').click(function() {
    $('.s2').fadeIn(500);
    $('.s3').hide();
})

$('.b4').click(function() {
    $('.s3').fadeIn(500);
    $('.s4').hide();
})




$('.s1 div input').click(function() {
        $('.n1').fadeIn(500);
        $('.n1').css('display','block')
    })

$('.s2 div input').click(function() {
        $('.n2').fadeIn(500);
        $('.n2').css('display','block')
    })

$('.s3 div input').click(function() {
        $('.n3').fadeIn(500);
        $('.n3').css('display','block')
    })

$('.s4 div input').click(function() {
    $('.btn_final').fadeIn(500);
    $('.btn_final').css('display','block')
    })

$('.btn_final').click(function() {
    $('form').submit();
})


{% endblock jquery %}