config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('feets/', include('feets.urls', namespace='feets')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('workshops/', include('workshops.urls', namespace='workshops')),
    path('knees/', include('knees.urls', namespace='knees')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path('', views.Home, name='home'),
    path('guide/', views.Guide, name='guide'),
    path('guide_tf', views.GuideTf, name='guide_tf'),
    path('guide_tt', views.GuideTt, name='guide_tt'),
    path('amputation', views.Amputation, name='amputation'),
    path('search', views.Search, name='search'),
    path('userstory', views.UserStory, name='userstory'),
    path('admin_page', views.AdminPage, name='admin-page'),

]

feets/urls.py
from django.shortcuts import render
from django.urls import path
from knees import views
from . import views


app_name = 'feets'

urlpatterns = [
    path('', views.FeetPage, name="feets"),
    path('search/', views.search, name='search'),
    path('<int:pk>/', views.FeetDetailView.as_view(), name='feet-detail'),
    path('feets_list_all', views.FeetListAllFilter, name='feets-list-all'),
    path('feets_admin_list/', views.FeetAdminListView.as_view(), name='feets-admin-list'),
    path('feets_admin_list/<int:pk>/', views.FeetAdminUpdateView.as_view(), name='feet-admin-update'),
]

knees/urls.py
from django.urls import path
from knees import views
from . import views


app_name = 'knees'

urlpatterns = [
    path('', views.Knees, name="knees"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.search, name='posts-list'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('create/', views.PostCreateView.as_view(), name='post-create'),
    path('<int:pk>/delete/',views.PostDeleteView.as_view(),name="post-delete",),
]

workshops/urls.py
from django.urls import path
from . import views

app_name = 'workshops'

urlpatterns = [
    path('', views.search, name='workshop-list'),
    path('workshops_admin_list/', views.WorkshopAdminListView.as_view(), name='workshops-admin-list'),
    path('workshops_admin_list/<int:pk>/delete', views.WorkshopAdminDeleteView.as_view(), name='workshop-admin-delete'),
    path('add/', views.WorkshopAdminCreateView.as_view(), name='workshop-admin-create'),
    path('workshops_admin_list/<int:pk>/update', views.WorkshopAdminUpdateView.as_view(), name='workshop-admin-update'),
    
]

templates/partials/footer.html
<h1></h1>

templates/partials/header.html
{% load static %}

<div class="header_bar">
    <div class="header_inner w-100">


        <div class='d-flex justify-content-between align-items-center h-100'>
            
            <div class='d-flex '>
                <div class='logo h-100'>
                    <a href="{% url 'core:home' %}"><img src="{% static 'images/logo.png' %}" class='w-100' /></a>
                </div>
                <div class='header_btn_container d-flex flex-column'>
                    <a href='{% url 'posts:posts-list' %}' id='guide' class='btn_header'>의족 FAQ</a>
                </div>
                <div class='header_btn_container d-flex flex-column'>
                    <a href='#' id='search' class='btn_header'>의족 찾기</a>
                    <div class='guide_drop_menu_display' id='search_menu'>
                        <div class='guide_drop_menu d-flex flex-column'>
                            <a href='{% url 'feets:feets' %}'>발</a>
                            <a href='{% url 'knees:knees' %}'>무릎</a>
                        </div>
                    </div>
                </div>
                <div class='header_btn_container d-flex flex-column'>
                    <a href='{% url 'core:userstory' %}' id='brand' class='btn_header'>유저 스토리</a>
                </div>
                <div class='header_btn_container d-flex flex-column'>
                    <a href='{% url 'workshops:workshop-list' %}' id='brand' class='btn_header'>의족 상담</a>
                </div>
            </div>    


            <div class='header_nav_icon'>
                <a href='{% url 'core:admin-page' %}'><i class="fas fa-user-cog"></i></a>
                <a href='#'><i class="fab fa-youtube"></i></a>
                <a href='#'><i class="fab fa-instagram"></i></a>
            </div>

        </div>

    </div>
</div>




<div class='mob_header_fixed'>
<div class='mob_header_bar justify-content-between'>

    <div class='mob_header_nav_icon'>
        <a data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
            <i class="fas fa-bars"></i>
        </a>

        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
            <div class="offcanvas-header">
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>

            <div class="offcanvas-body mob_menu_container">

                <div class='mob_menu_logo_container'>
                    <a href='{% url 'core:home' %}'><img class='mob_menu_logo' src='{% static 'images/logo.png' %}'></a>
                </div>

                <div>
                    <button onclick="location.href='{% url 'posts:posts-list'%}';">
                    의족 FAQ
                    </button>
                </div>

                <div>
                    <button class='d-flex flex-row justify-content-between'type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    <div>의족 찾기</div><div><i class="fas fa-plus"></i></div>
                    </button>
                    <div class="collapse" id="collapseExample">
                        <div class="card card-body">
                            <a class="dropdown-item mob_menu_dropdown" href="{% url 'feets:feets' %}">발</a>
                            <a class="dropdown-item mob_menu_dropdown" href='{% url 'knees:knees' %}'>무릎</a>
                        </div>
                    </div>
                    
                </div>

                <div>
                    <button onclick="location.href='{% url 'core:userstory'%}';">
                    유저 스토리
                    </button>
                </div>
                <div>
                    <button onclick="location.href='{% url 'workshops:workshop-list'%}';">
                    의족 상담
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div>
        <a href="{% url 'core:home' %}">
            <img class='mob_logo' src="{% static 'images/logo.png' %}">
        </a>
    </div>
</div>
</div>