config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('feets/', include('feets.urls', namespace='feets')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('workshops/', include('workshops.urls', namespace='workshops')),
    path('knees/', include('knees.urls', namespace='knees')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path('', views.Home, name='home'),
    path('guide/', views.Guide, name='guide'),
    path('guide_tf', views.GuideTf, name='guide_tf'),
    path('guide_tt', views.GuideTt, name='guide_tt'),
    path('amputation', views.Amputation, name='amputation'),
    path('search', views.Search, name='search'),
    path('userstory', views.UserStory, name='userstory'),
    path('admin_page', views.AdminPage, name='admin-page'),

]

feets/urls.py
from django.shortcuts import render
from django.urls import path
from knees import views
from . import views


app_name = 'feets'

urlpatterns = [
    path('', views.FeetPage, name="feets"),
    path('search/', views.search, name='search'),
    path('<int:pk>/', views.FeetDetailView.as_view(), name='feet-detail'),
    path('feets_list_all', views.FeetListAllFilter, name='feets-list-all'),
    path('feets_admin_list/', views.FeetAdminListView.as_view(), name='feets-admin-list'),
    path('feets_admin_list/<int:pk>/', views.FeetAdminUpdateView.as_view(), name='feet-admin-update'),
]

workshops/urls.py
from django.urls import path
from . import views

app_name = 'workshops'

urlpatterns = [
    path('', views.search, name='workshop-list'),
    path('workshops_admin_list/', views.WorkshopAdminListView.as_view(), name='workshops-admin-list'),
    path('workshops_admin_list/<int:pk>/delete', views.WorkshopAdminDeleteView.as_view(), name='workshop-admin-delete'),
    path('add/', views.WorkshopAdminCreateView.as_view(), name='workshop-admin-create'),
    path('workshops_admin_list/<int:pk>/update', views.WorkshopAdminUpdateView.as_view(), name='workshop-admin-update'),
    
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.http import request
from django.shortcuts import render

def Home(request):
    return render(request, 'home.html')


def Guide(request):
    return render(request, 'guide.html')

def GuideTf(request):
    return render(request, 'guide_tf.html')

def Amputation(request):
    return render(request, 'core/amputation.html')

def GuideTt(request):
    return render(request, 'guide_tt.html')

def Search(request):
    return render(request, 'core/search.html')
    
def UserStory(request):
    return render(request, 'core/userstory.html')

def AdminPage(request):
    return render(request, 'core/adminpage.html')

templates/core/adminpage.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel='stylesheet' href='{% static 'css/core/adminpage.css' %}'>
{% endblock style %}




{% block content %}
<div class='admin_page_container'>
    <div class='admin_page_btn'>
    <a href='#'>의족FAQ</a>
    </div>
    <div class='admin_page_btn'>
    <a href='{% url 'feets:feets-admin-list'%}'>발</a>
    </div>
    <div class='admin_page_btn'>
    <a href='{% url 'workshops:workshops-admin-list'%}'>대리점</a>
    </div>
</div>

{% endblock content %}

templates/core/adminpagefeet_list.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel='stylesheet' href='{% static 'css/core/adminpage_feet.css' %}'>
{% endblock style %}




{% block content %}
<div class='admin_feet_list_container'>
{% for feet in feets %}
    <div>
    <a href='{% url 'feets:feet-admin-update' feet.pk %}'>{{ feet.name }}</a>
    </div>
{% endfor %}
</div>

{% endblock content %}

templates/core/adminpagefeet_update.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel='stylesheet' href='{% static 'css/core/adminpage_feet.css' %}'>
{% endblock style %}




{% block content %}
<form method='post'>
    {% csrf_token %}
<div class='admin_form_container'>
<div>
{{form.code}}
</div>
<div>
{{form.name}}
</div>
<div>
{{form.description}}
</div>
<div>
활동등급{{form.mobis_grade}}
</div>
<div>
{{form.activity}}
</div>
<div>
{{form.function}}
</div>
<div>
{{form.age}}
</div>
<div>
{{form.rating}}
</div>
<div>
{{form.waterproof}}
</div>
<div>
가능범위{{form.brand}}
</div>
<div>
    <button type='submit' >완료</button>
</div>
</div>

</form>
{% endblock content %}

templates/core/adminpageworkshop_delete.html
{% extends '../base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block style %}

{% endblock style %}

{% block content %}
<form method='post'>
    {% csrf_token %}
<div class='d-flex flex-row' style='margin-top:100px'>
    <div class='back_btn' style='margin-left:100px; margin-right:100px'>
        <a onclick='goBack()'><i class="fas fa-arrow-left"></i> 뒤로가기</a>
    </div>

    <div>
    <button type="submit">삭제완료</button>
    </div>
</div>
</form>

{% endblock content%}

templates/core/adminpageworkshop_list.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel='stylesheet' href='{% static 'css/core/adminpage_feet.css' %}'>
{% endblock style %}




{% block content %}
<div class='admin_feet_list_container'>
    <div class='add_btn'>
    <a href='{% url 'workshops:workshop-admin-create' %}'>[추가]</a>
    </div>
{% for workshop in workshops %}
    <div>
    <a class='workshop_btn'href='{% url 'workshops:workshop-admin-update' workshop.pk %}'>{{ workshop.name }}</a><a href='{%url 'workshops:workshop-admin-delete' workshop.pk %}'>[삭제]</a>
    </div>
{% endfor %}
</div>

{% endblock content %}

templates/core/adminpageworkshop_update.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel='stylesheet' href='{% static 'css/core/adminpage_feet.css' %}'>
{% endblock style %}




{% block content %}
<form method='post'>
    {% csrf_token %}
<div class='admin_form_container'>
<div>
회사명{{form.name}}
</div>
<div>
지역{{form.location}}
</div>
<div>
주소{{form.address_text}}
</div>
<div>
연락처{{form.number}}
</div>
<div>
홈페이지{{form.link}}
</div>
<div>
주소 X좌표{{form.address_x}}
</div>
<div>
주소 Y좌표{{form.address_y}}
</div>

<div>
    <button type='submit' >완료</button>
</div>



</div>

</form>



{% endblock content %}

templates/core/amputation.html
{% extends 'base.html' %}
{% load static %}


{% block page_title %}오토복코리아헬스케어{% endblock page_title %}
{% block style %}
<link rel='stylesheet' href='{% static 'css/core/amputation.css' %}'>
{% endblock style %}
{% block content %}

<div class='home_container_1'>

    <div class='home_image_container'>
        <img src="{% static 'images/guide/guide(1).jpg' %}">
        <div class='home_title_container translate-middle'>
            <h1>절단 부위, 절단 길이별 차이를 확인하세요.</h1>
            <h2>아래 구분에 따라 제작 기간과 방법, 착용하는 제품이 달라집니다.
            </h2>
        </div>
    </div>

    <div class='home_image_container_2'>
        <img src="{% static 'images/amputation/foot_amputation.jpg' %}">
        <div class='home_title_container_2 translate-middle'>
            <h1>발가락 또는 발목 절단</h1>
            <h2>
            </h2>
        </div>
    </div>

    <div class='home_image_container_2'>
        <img src="{% static 'images/amputation/transtibial.jpg' %}">
        <div class='home_title_container_2 translate-middle'>
            <h1>하퇴 절단</h1>
            <h2>
            </h2>
        </div>
    </div>

    <div class='home_image_container_2'>
        <img src="{% static 'images/amputation/knee_disarticulation.jpg' %}">
        <div class='home_title_container_2 translate-middle'>
            <h1>무릎관절 이단</h1>
            <h2>
            </h2>
        </div>
    </div>


</div>
{% endblock content %}

templates/core/search.html
{% extends '../base.html' %}
{% load static %}

{% block style %}
<link rel='stylesheet' href='{% static 'css/core/search.css' %}'>
{% endblock style %}

{% block content %}


<div class='feet_container_1 d-flex flex-column'>
    <div class='feet_inner_1 translate-middle'>
        <img class='feet_inner_img' src="{% static 'images/feet_img/feet_img(2).png' %}">
    </div>
    <div class='feet_text_1 translate-middle feet_text'>
        <h1>나에게 맞는 의족 발 찾기</h1>
        <h2>카본발? 사이드 플렉스?<br>
            나에게 필요한 기능은 무엇일까요.<br>
            간단한 선택지를 통해 나에게 맞는<br>
            의족 발을 찾아보세요.
        </h2>
        <div class='btn_guide_start'>
            <a href='{% url 'feets:search' %}'>시작하기</a>
        </div>
    </div>
</div>

<div class='feet_container_2 d-flex flex-column'>
    <div class='feet_inner_2 translate-middle'>
        <img class='feet_inner_img' src="{% static 'images/core/search/search(2).png' %}">
    </div>
    <div class='feet_text_2 translate-middle feet_text'>
        <h1>나에게 맞는 의족 무릎 찾기</h1>
        <h2>MPK? 브레이크? 다축?<br>
        무엇보다 안정성이 중요한 무릎!<br>
        나에게 필요한 의지 무릎을 찾아보세요.</h2>
        <div class='btn_guide_start'>
            <a href='{% url 'feets:feets-list-all' %}'>시작하기</a>
        </div>
    </div>
</div>




{% endblock content %}


{% block jquery %}



{% endblock jquery %}

templates/core/userstory.html
{% extends '../base.html' %}
{% load static %}


{% block page_title %}오토복코리아헬스케어{% endblock page_title %}


{% block style %}
<link rel='stylesheet' href='{% static 'css/core/brandstory.css' %}'>
{% endblock style %}



{% block content %}



<div class='content_container'>
    <div class='text_container'>
        <div class='en_title'>
            <h2>
                Genium X3 User Story
            </h2>
        </div>
        <div class='ko_title'>
            <h3>
                지니움X3 유저 박지민님의 인터뷰 영상
            </h3>
        </div>
        <div class='d-flex'>
            <a class='show_btn' href='https://youtu.be/zb_L1bHZLZ0' target='_blank'><h4>지금 보러가기</h4></a>
        </div>
    </div>
    <div class='img_container'>
        <img class='img_geniumx3' src='{% static 'images/brandstory/geniumx3.png' %}'>
    </div>





</div>



{% endblock content %}

{% block jquery %}
$(document).ready(function(){
    localStorage.clear();
})
{% endblock jquery %}